plugins {
    kotlin("multiplatform")
    kotlin("kapt")
}

kotlin {
    kotlin {
        jvm()
        js().browser()

        sourceSets {
            val commonMain by getting {
                dependencies {
                    implementation(kotlin("stdlib"))
                    implementation(project(":core"))
                    configurations.get("kapt").dependencies.add(project(":lenses-annotation-processor"))
                }
                tasks.getByName("compileKotlinJs").dependsOn("kaptKotlinJvm")
            }
            val commonGenerated by creating {
                dependsOn(commonMain)
                kotlin.srcDir("build/generated/source/kaptKotlin/main")
            }
            val jvmMain by getting {
                dependsOn(commonGenerated)
                dependencies {
                    implementation(kotlin("stdlib"))
                    implementation(project(":core"))
                }
            }
            val jsMain by getting {
                dependsOn(commonGenerated)
                dependencies {
                    implementation(kotlin("stdlib-js"))
                    implementation(project(":core"))
                }
            }

        }
    }
}

