@file:Suppress("unused")

package dev.fritz2.dom.html

import dev.fritz2.dom.Tag
import kotlinx.coroutines.flow.Flow
import org.w3c.dom.*
import org.w3c.dom.events.Event
import org.w3c.dom.svg.SVGElement
import org.w3c.dom.svg.SVGPathElement
import org.w3c.fetch.RequestDestination

//FIXME: manche gibt es nicht?

//fun Tag<HTMLFormControlsCollection>.value(value: String) = attr("value", value)
//fun Tag<HTMLFormControlsCollection>.value(value: Flow<String>) = attr("value", value)
//fun Tag<HTMLOptionsCollection>.selectedIndex(value: Int) = attr("selectedIndex", value)
//fun Tag<HTMLOptionsCollection>.selectedIndex(value: Flow<Int>) = attr("selectedIndex", value)

fun Tag<HTMLElement>.title(value: String) = attr("title", value)
fun Tag<HTMLElement>.title(value: Flow<String>) = attr("title", value)
fun Tag<HTMLElement>.lang(value: String) = attr("lang", value)
fun Tag<HTMLElement>.lang(value: Flow<String>) = attr("lang", value)
fun Tag<HTMLElement>.translate(value: Boolean, trueValue: String = "") = attr("translate", value, trueValue)
fun Tag<HTMLElement>.translate(value: Flow<Boolean>, trueValue: String = "") = attr("translate", value, trueValue)
fun Tag<HTMLElement>.dir(value: String) = attr("dir", value)
fun Tag<HTMLElement>.dir(value: Flow<String>) = attr("dir", value)
fun Tag<HTMLElement>.hidden(value: Boolean, trueValue: String = "") = attr("hidden", value, trueValue)
fun Tag<HTMLElement>.hidden(value: Flow<Boolean>, trueValue: String = "") = attr("hidden", value, trueValue)
fun Tag<HTMLElement>.tabIndex(value: Int) = attr("tabIndex", value)
fun Tag<HTMLElement>.tabIndex(value: Flow<Int>) = attr("tabIndex", value)
fun Tag<HTMLElement>.accessKey(value: String) = attr("accessKey", value)
fun Tag<HTMLElement>.accessKey(value: Flow<String>) = attr("accessKey", value)
fun Tag<HTMLElement>.draggable(value: Boolean, trueValue: String = "") = attr("draggable", value, trueValue)
fun Tag<HTMLElement>.draggable(value: Flow<Boolean>, trueValue: String = "") = attr("draggable", value, trueValue)
fun Tag<HTMLElement>.contextMenu(value: HTMLMenuElement?) = attr("contextMenu", value)
fun Tag<HTMLElement>.contextMenu(value: Flow<HTMLMenuElement?>) = attr("contextMenu", value)
fun Tag<HTMLElement>.spellcheck(value: Boolean, trueValue: String = "") = attr("spellcheck", value, trueValue)
fun Tag<HTMLElement>.spellcheck(value: Flow<Boolean>, trueValue: String = "") = attr("spellcheck", value, trueValue)
fun Tag<HTMLElement>.innerText(value: String) = attr("innerText", value)
fun Tag<HTMLElement>.innerText(value: Flow<String>) = attr("innerText", value)
fun Tag<HTMLHtmlElement>.version(value: String) = attr("version", value)
fun Tag<HTMLHtmlElement>.version(value: Flow<String>) = attr("version", value)
fun Tag<HTMLTitleElement>.text(value: String) = attr("text", value)
fun Tag<HTMLTitleElement>.text(value: Flow<String>) = attr("text", value)
fun Tag<HTMLBaseElement>.href(value: String) = attr("href", value)
fun Tag<HTMLBaseElement>.href(value: Flow<String>) = attr("href", value)
fun Tag<HTMLBaseElement>.target(value: String) = attr("target", value)
fun Tag<HTMLBaseElement>.target(value: Flow<String>) = attr("target", value)
fun Tag<HTMLLinkElement>.href(value: String) = attr("href", value)
fun Tag<HTMLLinkElement>.href(value: Flow<String>) = attr("href", value)
fun Tag<HTMLLinkElement>.crossOrigin(value: String?) = attr("crossOrigin", value)
fun Tag<HTMLLinkElement>.crossOrigin(value: Flow<String?>) = attr("crossOrigin", value)
fun Tag<HTMLLinkElement>.rel(value: String) = attr("rel", value)
fun Tag<HTMLLinkElement>.rel(value: Flow<String>) = attr("rel", value)
fun Tag<HTMLLinkElement>.`as`(value: RequestDestination) = attr("`as`", value)
fun Tag<HTMLLinkElement>.`as`(value: Flow<RequestDestination>) = attr("`as`", value)
fun Tag<HTMLLinkElement>.media(value: String) = attr("media", value)
fun Tag<HTMLLinkElement>.media(value: Flow<String>) = attr("media", value)
fun Tag<HTMLLinkElement>.nonce(value: String) = attr("nonce", value)
fun Tag<HTMLLinkElement>.nonce(value: Flow<String>) = attr("nonce", value)
fun Tag<HTMLLinkElement>.hreflang(value: String) = attr("hreflang", value)
fun Tag<HTMLLinkElement>.hreflang(value: Flow<String>) = attr("hreflang", value)
fun Tag<HTMLLinkElement>.type(value: String) = attr("type", value)
fun Tag<HTMLLinkElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLLinkElement>.referrerPolicy(value: String) = attr("referrerPolicy", value)
fun Tag<HTMLLinkElement>.referrerPolicy(value: Flow<String>) = attr("referrerPolicy", value)
fun Tag<HTMLLinkElement>.charset(value: String) = attr("charset", value)
fun Tag<HTMLLinkElement>.charset(value: Flow<String>) = attr("charset", value)
fun Tag<HTMLLinkElement>.rev(value: String) = attr("rev", value)
fun Tag<HTMLLinkElement>.rev(value: Flow<String>) = attr("rev", value)
fun Tag<HTMLLinkElement>.target(value: String) = attr("target", value)
fun Tag<HTMLLinkElement>.target(value: Flow<String>) = attr("target", value)
fun Tag<HTMLLinkElement>.scope(value: String) = attr("scope", value)
fun Tag<HTMLLinkElement>.scope(value: Flow<String>) = attr("scope", value)
fun Tag<HTMLLinkElement>.workerType(value: WorkerType) = attr("workerType", value)
fun Tag<HTMLLinkElement>.workerType(value: Flow<WorkerType>) = attr("workerType", value)
fun Tag<HTMLMetaElement>.name(value: String) = attr("name", value)
fun Tag<HTMLMetaElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLMetaElement>.httpEquiv(value: String) = attr("httpEquiv", value)
fun Tag<HTMLMetaElement>.httpEquiv(value: Flow<String>) = attr("httpEquiv", value)
fun Tag<HTMLMetaElement>.content(value: String) = attr("content", value)
fun Tag<HTMLMetaElement>.content(value: Flow<String>) = attr("content", value)
fun Tag<HTMLMetaElement>.scheme(value: String) = attr("scheme", value)
fun Tag<HTMLMetaElement>.scheme(value: Flow<String>) = attr("scheme", value)
fun Tag<HTMLStyleElement>.media(value: String) = attr("media", value)
fun Tag<HTMLStyleElement>.media(value: Flow<String>) = attr("media", value)
fun Tag<HTMLStyleElement>.nonce(value: String) = attr("nonce", value)
fun Tag<HTMLStyleElement>.nonce(value: Flow<String>) = attr("nonce", value)
fun Tag<HTMLStyleElement>.type(value: String) = attr("type", value)
fun Tag<HTMLStyleElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLBodyElement>.text(value: String) = attr("text", value)
fun Tag<HTMLBodyElement>.text(value: Flow<String>) = attr("text", value)
fun Tag<HTMLBodyElement>.link(value: String) = attr("link", value)
fun Tag<HTMLBodyElement>.link(value: Flow<String>) = attr("link", value)
fun Tag<HTMLBodyElement>.vLink(value: String) = attr("vLink", value)
fun Tag<HTMLBodyElement>.vLink(value: Flow<String>) = attr("vLink", value)
fun Tag<HTMLBodyElement>.aLink(value: String) = attr("aLink", value)
fun Tag<HTMLBodyElement>.aLink(value: Flow<String>) = attr("aLink", value)
fun Tag<HTMLBodyElement>.bgColor(value: String) = attr("bgColor", value)
fun Tag<HTMLBodyElement>.bgColor(value: Flow<String>) = attr("bgColor", value)
fun Tag<HTMLBodyElement>.background(value: String) = attr("background", value)
fun Tag<HTMLBodyElement>.background(value: Flow<String>) = attr("background", value)
fun Tag<HTMLHeadingElement>.align(value: String) = attr("align", value)
fun Tag<HTMLHeadingElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLParagraphElement>.align(value: String) = attr("align", value)
fun Tag<HTMLParagraphElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLHRElement>.align(value: String) = attr("align", value)
fun Tag<HTMLHRElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLHRElement>.color(value: String) = attr("color", value)
fun Tag<HTMLHRElement>.color(value: Flow<String>) = attr("color", value)
fun Tag<HTMLHRElement>.noShade(value: Boolean, trueValue: String = "") = attr("noShade", value, trueValue)
fun Tag<HTMLHRElement>.noShade(value: Flow<Boolean>, trueValue: String = "") = attr("noShade", value, trueValue)
fun Tag<HTMLHRElement>.size(value: String) = attr("size", value)
fun Tag<HTMLHRElement>.size(value: Flow<String>) = attr("size", value)
fun Tag<HTMLHRElement>.width(value: String) = attr("width", value)
fun Tag<HTMLHRElement>.width(value: Flow<String>) = attr("width", value)
fun Tag<HTMLPreElement>.width(value: Int) = attr("width", value)
fun Tag<HTMLPreElement>.width(value: Flow<Int>) = attr("width", value)
fun Tag<HTMLQuoteElement>.cite(value: String) = attr("cite", value)
fun Tag<HTMLQuoteElement>.cite(value: Flow<String>) = attr("cite", value)
fun Tag<HTMLOListElement>.reversed(value: Boolean, trueValue: String = "") = attr("reversed", value, trueValue)
fun Tag<HTMLOListElement>.reversed(value: Flow<Boolean>, trueValue: String = "") = attr("reversed", value, trueValue)
fun Tag<HTMLOListElement>.start(value: Int) = attr("start", value)
fun Tag<HTMLOListElement>.start(value: Flow<Int>) = attr("start", value)
fun Tag<HTMLOListElement>.type(value: String) = attr("type", value)
fun Tag<HTMLOListElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLOListElement>.compact(value: Boolean, trueValue: String = "") = attr("compact", value, trueValue)
fun Tag<HTMLOListElement>.compact(value: Flow<Boolean>, trueValue: String = "") = attr("compact", value, trueValue)
fun Tag<HTMLUListElement>.compact(value: Boolean, trueValue: String = "") = attr("compact", value, trueValue)
fun Tag<HTMLUListElement>.compact(value: Flow<Boolean>, trueValue: String = "") = attr("compact", value, trueValue)
fun Tag<HTMLUListElement>.type(value: String) = attr("type", value)
fun Tag<HTMLUListElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLLIElement>.value(value: Int) = attr("value", value)
fun Tag<HTMLLIElement>.value(value: Flow<Int>) = attr("value", value)
fun Tag<HTMLLIElement>.type(value: String) = attr("type", value)
fun Tag<HTMLLIElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLDListElement>.compact(value: Boolean, trueValue: String = "") = attr("compact", value, trueValue)
fun Tag<HTMLDListElement>.compact(value: Flow<Boolean>, trueValue: String = "") = attr("compact", value, trueValue)
fun Tag<HTMLDivElement>.align(value: String) = attr("align", value)
fun Tag<HTMLDivElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLAnchorElement>.target(value: String) = attr("target", value)
fun Tag<HTMLAnchorElement>.target(value: Flow<String>) = attr("target", value)
fun Tag<HTMLAnchorElement>.download(value: String) = attr("download", value)
fun Tag<HTMLAnchorElement>.download(value: Flow<String>) = attr("download", value)
fun Tag<HTMLAnchorElement>.ping(value: String) = attr("ping", value)
fun Tag<HTMLAnchorElement>.ping(value: Flow<String>) = attr("ping", value)
fun Tag<HTMLAnchorElement>.rel(value: String) = attr("rel", value)
fun Tag<HTMLAnchorElement>.rel(value: Flow<String>) = attr("rel", value)
fun Tag<HTMLAnchorElement>.href(value: String) = attr("href", value)
fun Tag<HTMLAnchorElement>.href(value: Flow<String>) = attr("href", value)
fun Tag<HTMLAnchorElement>.type(value: String) = attr("type", value)
fun Tag<HTMLAnchorElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLAnchorElement>.text(value: String) = attr("text", value)
fun Tag<HTMLAnchorElement>.text(value: Flow<String>) = attr("text", value)
fun Tag<HTMLAnchorElement>.referrerPolicy(value: String) = attr("referrerPolicy", value)
fun Tag<HTMLAnchorElement>.referrerPolicy(value: Flow<String>) = attr("referrerPolicy", value)
fun Tag<HTMLAnchorElement>.coords(value: String) = attr("coords", value)
fun Tag<HTMLAnchorElement>.coords(value: Flow<String>) = attr("coords", value)
fun Tag<HTMLAnchorElement>.charset(value: String) = attr("charset", value)
fun Tag<HTMLAnchorElement>.charset(value: Flow<String>) = attr("charset", value)
fun Tag<HTMLAnchorElement>.name(value: String) = attr("name", value)
fun Tag<HTMLAnchorElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLAnchorElement>.rev(value: String) = attr("rev", value)
fun Tag<HTMLAnchorElement>.rev(value: Flow<String>) = attr("rev", value)
fun Tag<HTMLAnchorElement>.shape(value: String) = attr("shape", value)
fun Tag<HTMLAnchorElement>.shape(value: Flow<String>) = attr("shape", value)
fun Tag<HTMLDataElement>.value(value: String) = attr("value", value)
fun Tag<HTMLDataElement>.value(value: Flow<String>) = attr("value", value)
fun Tag<HTMLTimeElement>.dateTime(value: String) = attr("dateTime", value)
fun Tag<HTMLTimeElement>.dateTime(value: Flow<String>) = attr("dateTime", value)
fun Tag<HTMLBRElement>.clear(value: String) = attr("clear", value)
fun Tag<HTMLBRElement>.clear(value: Flow<String>) = attr("clear", value)
fun Tag<HTMLModElement>.cite(value: String) = attr("cite", value)
fun Tag<HTMLModElement>.cite(value: Flow<String>) = attr("cite", value)
fun Tag<HTMLModElement>.dateTime(value: String) = attr("dateTime", value)
fun Tag<HTMLModElement>.dateTime(value: Flow<String>) = attr("dateTime", value)
fun Tag<HTMLSourceElement>.src(value: String) = attr("src", value)
fun Tag<HTMLSourceElement>.src(value: Flow<String>) = attr("src", value)
fun Tag<HTMLSourceElement>.type(value: String) = attr("type", value)
fun Tag<HTMLSourceElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLSourceElement>.srcset(value: String) = attr("srcset", value)
fun Tag<HTMLSourceElement>.srcset(value: Flow<String>) = attr("srcset", value)
fun Tag<HTMLSourceElement>.sizes(value: String) = attr("sizes", value)
fun Tag<HTMLSourceElement>.sizes(value: Flow<String>) = attr("sizes", value)
fun Tag<HTMLSourceElement>.media(value: String) = attr("media", value)
fun Tag<HTMLSourceElement>.media(value: Flow<String>) = attr("media", value)
fun Tag<HTMLImageElement>.alt(value: String) = attr("alt", value)
fun Tag<HTMLImageElement>.alt(value: Flow<String>) = attr("alt", value)
fun Tag<HTMLImageElement>.src(value: String) = attr("src", value)
fun Tag<HTMLImageElement>.src(value: Flow<String>) = attr("src", value)
fun Tag<HTMLImageElement>.srcset(value: String) = attr("srcset", value)
fun Tag<HTMLImageElement>.srcset(value: Flow<String>) = attr("srcset", value)
fun Tag<HTMLImageElement>.sizes(value: String) = attr("sizes", value)
fun Tag<HTMLImageElement>.sizes(value: Flow<String>) = attr("sizes", value)
fun Tag<HTMLImageElement>.crossOrigin(value: String?) = attr("crossOrigin", value)
fun Tag<HTMLImageElement>.crossOrigin(value: Flow<String?>) = attr("crossOrigin", value)
fun Tag<HTMLImageElement>.useMap(value: String) = attr("useMap", value)
fun Tag<HTMLImageElement>.useMap(value: Flow<String>) = attr("useMap", value)
fun Tag<HTMLImageElement>.isMap(value: Boolean, trueValue: String = "") = attr("isMap", value, trueValue)
fun Tag<HTMLImageElement>.isMap(value: Flow<Boolean>, trueValue: String = "") = attr("isMap", value, trueValue)
fun Tag<HTMLImageElement>.width(value: Int) = attr("width", value)
fun Tag<HTMLImageElement>.width(value: Flow<Int>) = attr("width", value)
fun Tag<HTMLImageElement>.height(value: Int) = attr("height", value)
fun Tag<HTMLImageElement>.height(value: Flow<Int>) = attr("height", value)
fun Tag<HTMLImageElement>.referrerPolicy(value: String) = attr("referrerPolicy", value)
fun Tag<HTMLImageElement>.referrerPolicy(value: Flow<String>) = attr("referrerPolicy", value)
fun Tag<HTMLImageElement>.name(value: String) = attr("name", value)
fun Tag<HTMLImageElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLImageElement>.lowsrc(value: String) = attr("lowsrc", value)
fun Tag<HTMLImageElement>.lowsrc(value: Flow<String>) = attr("lowsrc", value)
fun Tag<HTMLImageElement>.align(value: String) = attr("align", value)
fun Tag<HTMLImageElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLImageElement>.hspace(value: Int) = attr("hspace", value)
fun Tag<HTMLImageElement>.hspace(value: Flow<Int>) = attr("hspace", value)
fun Tag<HTMLImageElement>.vspace(value: Int) = attr("vspace", value)
fun Tag<HTMLImageElement>.vspace(value: Flow<Int>) = attr("vspace", value)
fun Tag<HTMLImageElement>.longDesc(value: String) = attr("longDesc", value)
fun Tag<HTMLImageElement>.longDesc(value: Flow<String>) = attr("longDesc", value)
fun Tag<HTMLImageElement>.border(value: String) = attr("border", value)
fun Tag<HTMLImageElement>.border(value: Flow<String>) = attr("border", value)
fun Tag<HTMLIFrameElement>.src(value: String) = attr("src", value)
fun Tag<HTMLIFrameElement>.src(value: Flow<String>) = attr("src", value)
fun Tag<HTMLIFrameElement>.srcdoc(value: String) = attr("srcdoc", value)
fun Tag<HTMLIFrameElement>.srcdoc(value: Flow<String>) = attr("srcdoc", value)
fun Tag<HTMLIFrameElement>.name(value: String) = attr("name", value)
fun Tag<HTMLIFrameElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLIFrameElement>.allowFullscreen(value: Boolean, trueValue: String = "") = attr("allowFullscreen", value, trueValue)
fun Tag<HTMLIFrameElement>.allowFullscreen(value: Flow<Boolean>, trueValue: String = "") = attr("allowFullscreen", value, trueValue)
fun Tag<HTMLIFrameElement>.allowUserMedia(value: Boolean, trueValue: String = "") = attr("allowUserMedia", value, trueValue)
fun Tag<HTMLIFrameElement>.allowUserMedia(value: Flow<Boolean>, trueValue: String = "") = attr("allowUserMedia", value, trueValue)
fun Tag<HTMLIFrameElement>.width(value: String) = attr("width", value)
fun Tag<HTMLIFrameElement>.width(value: Flow<String>) = attr("width", value)
fun Tag<HTMLIFrameElement>.height(value: String) = attr("height", value)
fun Tag<HTMLIFrameElement>.height(value: Flow<String>) = attr("height", value)
fun Tag<HTMLIFrameElement>.referrerPolicy(value: String) = attr("referrerPolicy", value)
fun Tag<HTMLIFrameElement>.referrerPolicy(value: Flow<String>) = attr("referrerPolicy", value)
fun Tag<HTMLIFrameElement>.align(value: String) = attr("align", value)
fun Tag<HTMLIFrameElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLIFrameElement>.scrolling(value: String) = attr("scrolling", value)
fun Tag<HTMLIFrameElement>.scrolling(value: Flow<String>) = attr("scrolling", value)
fun Tag<HTMLIFrameElement>.frameBorder(value: String) = attr("frameBorder", value)
fun Tag<HTMLIFrameElement>.frameBorder(value: Flow<String>) = attr("frameBorder", value)
fun Tag<HTMLIFrameElement>.longDesc(value: String) = attr("longDesc", value)
fun Tag<HTMLIFrameElement>.longDesc(value: Flow<String>) = attr("longDesc", value)
fun Tag<HTMLIFrameElement>.marginHeight(value: String) = attr("marginHeight", value)
fun Tag<HTMLIFrameElement>.marginHeight(value: Flow<String>) = attr("marginHeight", value)
fun Tag<HTMLIFrameElement>.marginWidth(value: String) = attr("marginWidth", value)
fun Tag<HTMLIFrameElement>.marginWidth(value: Flow<String>) = attr("marginWidth", value)
fun Tag<HTMLEmbedElement>.src(value: String) = attr("src", value)
fun Tag<HTMLEmbedElement>.src(value: Flow<String>) = attr("src", value)
fun Tag<HTMLEmbedElement>.type(value: String) = attr("type", value)
fun Tag<HTMLEmbedElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLEmbedElement>.width(value: String) = attr("width", value)
fun Tag<HTMLEmbedElement>.width(value: Flow<String>) = attr("width", value)
fun Tag<HTMLEmbedElement>.height(value: String) = attr("height", value)
fun Tag<HTMLEmbedElement>.height(value: Flow<String>) = attr("height", value)
fun Tag<HTMLEmbedElement>.align(value: String) = attr("align", value)
fun Tag<HTMLEmbedElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLEmbedElement>.name(value: String) = attr("name", value)
fun Tag<HTMLEmbedElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLObjectElement>.data(value: String) = attr("data", value)
fun Tag<HTMLObjectElement>.data(value: Flow<String>) = attr("data", value)
fun Tag<HTMLObjectElement>.type(value: String) = attr("type", value)
fun Tag<HTMLObjectElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLObjectElement>.typeMustMatch(value: Boolean, trueValue: String = "") = attr("typeMustMatch", value, trueValue)
fun Tag<HTMLObjectElement>.typeMustMatch(value: Flow<Boolean>, trueValue: String = "") = attr("typeMustMatch", value, trueValue)
fun Tag<HTMLObjectElement>.name(value: String) = attr("name", value)
fun Tag<HTMLObjectElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLObjectElement>.useMap(value: String) = attr("useMap", value)
fun Tag<HTMLObjectElement>.useMap(value: Flow<String>) = attr("useMap", value)
fun Tag<HTMLObjectElement>.width(value: String) = attr("width", value)
fun Tag<HTMLObjectElement>.width(value: Flow<String>) = attr("width", value)
fun Tag<HTMLObjectElement>.height(value: String) = attr("height", value)
fun Tag<HTMLObjectElement>.height(value: Flow<String>) = attr("height", value)
fun Tag<HTMLObjectElement>.align(value: String) = attr("align", value)
fun Tag<HTMLObjectElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLObjectElement>.archive(value: String) = attr("archive", value)
fun Tag<HTMLObjectElement>.archive(value: Flow<String>) = attr("archive", value)
fun Tag<HTMLObjectElement>.code(value: String) = attr("code", value)
fun Tag<HTMLObjectElement>.code(value: Flow<String>) = attr("code", value)
fun Tag<HTMLObjectElement>.declare(value: Boolean, trueValue: String = "") = attr("declare", value, trueValue)
fun Tag<HTMLObjectElement>.declare(value: Flow<Boolean>, trueValue: String = "") = attr("declare", value, trueValue)
fun Tag<HTMLObjectElement>.hspace(value: Int) = attr("hspace", value)
fun Tag<HTMLObjectElement>.hspace(value: Flow<Int>) = attr("hspace", value)
fun Tag<HTMLObjectElement>.standby(value: String) = attr("standby", value)
fun Tag<HTMLObjectElement>.standby(value: Flow<String>) = attr("standby", value)
fun Tag<HTMLObjectElement>.vspace(value: Int) = attr("vspace", value)
fun Tag<HTMLObjectElement>.vspace(value: Flow<Int>) = attr("vspace", value)
fun Tag<HTMLObjectElement>.codeBase(value: String) = attr("codeBase", value)
fun Tag<HTMLObjectElement>.codeBase(value: Flow<String>) = attr("codeBase", value)
fun Tag<HTMLObjectElement>.codeType(value: String) = attr("codeType", value)
fun Tag<HTMLObjectElement>.codeType(value: Flow<String>) = attr("codeType", value)
fun Tag<HTMLObjectElement>.border(value: String) = attr("border", value)
fun Tag<HTMLObjectElement>.border(value: Flow<String>) = attr("border", value)
fun Tag<HTMLParamElement>.name(value: String) = attr("name", value)
fun Tag<HTMLParamElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLParamElement>.value(value: String) = attr("value", value)
fun Tag<HTMLParamElement>.value(value: Flow<String>) = attr("value", value)
fun Tag<HTMLParamElement>.type(value: String) = attr("type", value)
fun Tag<HTMLParamElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLParamElement>.valueType(value: String) = attr("valueType", value)
fun Tag<HTMLParamElement>.valueType(value: Flow<String>) = attr("valueType", value)
fun Tag<HTMLVideoElement>.width(value: Int) = attr("width", value)
fun Tag<HTMLVideoElement>.width(value: Flow<Int>) = attr("width", value)
fun Tag<HTMLVideoElement>.height(value: Int) = attr("height", value)
fun Tag<HTMLVideoElement>.height(value: Flow<Int>) = attr("height", value)
fun Tag<HTMLVideoElement>.poster(value: String) = attr("poster", value)
fun Tag<HTMLVideoElement>.poster(value: Flow<String>) = attr("poster", value)
fun Tag<HTMLVideoElement>.playsInline(value: Boolean, trueValue: String = "") = attr("playsInline", value, trueValue)
fun Tag<HTMLVideoElement>.playsInline(value: Flow<Boolean>, trueValue: String = "") = attr("playsInline", value, trueValue)
fun Tag<HTMLTrackElement>.kind(value: String) = attr("kind", value)
fun Tag<HTMLTrackElement>.kind(value: Flow<String>) = attr("kind", value)
fun Tag<HTMLTrackElement>.src(value: String) = attr("src", value)
fun Tag<HTMLTrackElement>.src(value: Flow<String>) = attr("src", value)
fun Tag<HTMLTrackElement>.srclang(value: String) = attr("srclang", value)
fun Tag<HTMLTrackElement>.srclang(value: Flow<String>) = attr("srclang", value)
fun Tag<HTMLTrackElement>.label(value: String) = attr("label", value)
fun Tag<HTMLTrackElement>.label(value: Flow<String>) = attr("label", value)
fun Tag<HTMLTrackElement>.default(value: Boolean, trueValue: String = "") = attr("default", value, trueValue)
fun Tag<HTMLTrackElement>.default(value: Flow<Boolean>, trueValue: String = "") = attr("default", value, trueValue)
fun Tag<HTMLMediaElement>.src(value: String) = attr("src", value)
fun Tag<HTMLMediaElement>.src(value: Flow<String>) = attr("src", value)
fun Tag<HTMLMediaElement>.srcObject(value: MediaProvider?) = attr("srcObject", value)
fun Tag<HTMLMediaElement>.srcObject(value: Flow<MediaProvider?>) = attr("srcObject", value)
fun Tag<HTMLMediaElement>.crossOrigin(value: String?) = attr("crossOrigin", value)
fun Tag<HTMLMediaElement>.crossOrigin(value: Flow<String?>) = attr("crossOrigin", value)
fun Tag<HTMLMediaElement>.preload(value: String) = attr("preload", value)
fun Tag<HTMLMediaElement>.preload(value: Flow<String>) = attr("preload", value)
fun Tag<HTMLMediaElement>.currentTime(value: Double) = attr("currentTime", value)
fun Tag<HTMLMediaElement>.currentTime(value: Flow<Double>) = attr("currentTime", value)
fun Tag<HTMLMediaElement>.defaultPlaybackRate(value: Double) = attr("defaultPlaybackRate", value)
fun Tag<HTMLMediaElement>.defaultPlaybackRate(value: Flow<Double>) = attr("defaultPlaybackRate", value)
fun Tag<HTMLMediaElement>.playbackRate(value: Double) = attr("playbackRate", value)
fun Tag<HTMLMediaElement>.playbackRate(value: Flow<Double>) = attr("playbackRate", value)
fun Tag<HTMLMediaElement>.autoplay(value: Boolean, trueValue: String = "") = attr("autoplay", value, trueValue)
fun Tag<HTMLMediaElement>.autoplay(value: Flow<Boolean>, trueValue: String = "") = attr("autoplay", value, trueValue)
fun Tag<HTMLMediaElement>.loop(value: Boolean, trueValue: String = "") = attr("loop", value, trueValue)
fun Tag<HTMLMediaElement>.loop(value: Flow<Boolean>, trueValue: String = "") = attr("loop", value, trueValue)
fun Tag<HTMLMediaElement>.controls(value: Boolean, trueValue: String = "") = attr("controls", value, trueValue)
fun Tag<HTMLMediaElement>.controls(value: Flow<Boolean>, trueValue: String = "") = attr("controls", value, trueValue)
fun Tag<HTMLMediaElement>.volume(value: Double) = attr("volume", value)
fun Tag<HTMLMediaElement>.volume(value: Flow<Double>) = attr("volume", value)
fun Tag<HTMLMediaElement>.muted(value: Boolean, trueValue: String = "") = attr("muted", value, trueValue)
fun Tag<HTMLMediaElement>.muted(value: Flow<Boolean>, trueValue: String = "") = attr("muted", value, trueValue)
fun Tag<HTMLMediaElement>.defaultMuted(value: Boolean, trueValue: String = "") = attr("defaultMuted", value, trueValue)
fun Tag<HTMLMediaElement>.defaultMuted(value: Flow<Boolean>, trueValue: String = "") = attr("defaultMuted", value, trueValue)
fun Tag<HTMLMediaElement>.onencrypted(value: ((Event) -> dynamic)?) = attr("onencrypted", value)
fun Tag<HTMLMediaElement>.onencrypted(value: Flow<((Event) -> dynamic)?>) = attr("onencrypted", value)
fun Tag<HTMLMediaElement>.onwaitingforkey(value: ((Event) -> dynamic)?) = attr("onwaitingforkey", value)
fun Tag<HTMLMediaElement>.onwaitingforkey(value: Flow<((Event) -> dynamic)?>) = attr("onwaitingforkey", value)
fun Tag<HTMLMapElement>.name(value: String) = attr("name", value)
fun Tag<HTMLMapElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLAreaElement>.alt(value: String) = attr("alt", value)
fun Tag<HTMLAreaElement>.alt(value: Flow<String>) = attr("alt", value)
fun Tag<HTMLAreaElement>.coords(value: String) = attr("coords", value)
fun Tag<HTMLAreaElement>.coords(value: Flow<String>) = attr("coords", value)
fun Tag<HTMLAreaElement>.shape(value: String) = attr("shape", value)
fun Tag<HTMLAreaElement>.shape(value: Flow<String>) = attr("shape", value)
fun Tag<HTMLAreaElement>.target(value: String) = attr("target", value)
fun Tag<HTMLAreaElement>.target(value: Flow<String>) = attr("target", value)
fun Tag<HTMLAreaElement>.download(value: String) = attr("download", value)
fun Tag<HTMLAreaElement>.download(value: Flow<String>) = attr("download", value)
fun Tag<HTMLAreaElement>.ping(value: String) = attr("ping", value)
fun Tag<HTMLAreaElement>.ping(value: Flow<String>) = attr("ping", value)
fun Tag<HTMLAreaElement>.rel(value: String) = attr("rel", value)
fun Tag<HTMLAreaElement>.rel(value: Flow<String>) = attr("rel", value)
fun Tag<HTMLAreaElement>.referrerPolicy(value: String) = attr("referrerPolicy", value)
fun Tag<HTMLAreaElement>.referrerPolicy(value: Flow<String>) = attr("referrerPolicy", value)
fun Tag<HTMLAreaElement>.noHref(value: Boolean, trueValue: String = "") = attr("noHref", value, trueValue)
fun Tag<HTMLAreaElement>.noHref(value: Flow<Boolean>, trueValue: String = "") = attr("noHref", value, trueValue)
fun Tag<HTMLTableElement>.caption(value: HTMLTableCaptionElement?) = attr("caption", value)
fun Tag<HTMLTableElement>.caption(value: Flow<HTMLTableCaptionElement?>) = attr("caption", value)
fun Tag<HTMLTableElement>.tHead(value: HTMLTableSectionElement?) = attr("tHead", value)
fun Tag<HTMLTableElement>.tHead(value: Flow<HTMLTableSectionElement?>) = attr("tHead", value)
fun Tag<HTMLTableElement>.tFoot(value: HTMLTableSectionElement?) = attr("tFoot", value)
fun Tag<HTMLTableElement>.tFoot(value: Flow<HTMLTableSectionElement?>) = attr("tFoot", value)
fun Tag<HTMLTableElement>.align(value: String) = attr("align", value)
fun Tag<HTMLTableElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLTableElement>.border(value: String) = attr("border", value)
fun Tag<HTMLTableElement>.border(value: Flow<String>) = attr("border", value)
fun Tag<HTMLTableElement>.frame(value: String) = attr("frame", value)
fun Tag<HTMLTableElement>.frame(value: Flow<String>) = attr("frame", value)
fun Tag<HTMLTableElement>.rules(value: String) = attr("rules", value)
fun Tag<HTMLTableElement>.rules(value: Flow<String>) = attr("rules", value)
fun Tag<HTMLTableElement>.summary(value: String) = attr("summary", value)
fun Tag<HTMLTableElement>.summary(value: Flow<String>) = attr("summary", value)
fun Tag<HTMLTableElement>.width(value: String) = attr("width", value)
fun Tag<HTMLTableElement>.width(value: Flow<String>) = attr("width", value)
fun Tag<HTMLTableElement>.bgColor(value: String) = attr("bgColor", value)
fun Tag<HTMLTableElement>.bgColor(value: Flow<String>) = attr("bgColor", value)
fun Tag<HTMLTableElement>.cellPadding(value: String) = attr("cellPadding", value)
fun Tag<HTMLTableElement>.cellPadding(value: Flow<String>) = attr("cellPadding", value)
fun Tag<HTMLTableElement>.cellSpacing(value: String) = attr("cellSpacing", value)
fun Tag<HTMLTableElement>.cellSpacing(value: Flow<String>) = attr("cellSpacing", value)
fun Tag<HTMLTableCaptionElement>.align(value: String) = attr("align", value)
fun Tag<HTMLTableCaptionElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLTableColElement>.span(value: Int) = attr("span", value)
fun Tag<HTMLTableColElement>.span(value: Flow<Int>) = attr("span", value)
fun Tag<HTMLTableColElement>.align(value: String) = attr("align", value)
fun Tag<HTMLTableColElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLTableColElement>.ch(value: String) = attr("ch", value)
fun Tag<HTMLTableColElement>.ch(value: Flow<String>) = attr("ch", value)
fun Tag<HTMLTableColElement>.chOff(value: String) = attr("chOff", value)
fun Tag<HTMLTableColElement>.chOff(value: Flow<String>) = attr("chOff", value)
fun Tag<HTMLTableColElement>.vAlign(value: String) = attr("vAlign", value)
fun Tag<HTMLTableColElement>.vAlign(value: Flow<String>) = attr("vAlign", value)
fun Tag<HTMLTableColElement>.width(value: String) = attr("width", value)
fun Tag<HTMLTableColElement>.width(value: Flow<String>) = attr("width", value)
fun Tag<HTMLTableSectionElement>.align(value: String) = attr("align", value)
fun Tag<HTMLTableSectionElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLTableSectionElement>.ch(value: String) = attr("ch", value)
fun Tag<HTMLTableSectionElement>.ch(value: Flow<String>) = attr("ch", value)
fun Tag<HTMLTableSectionElement>.chOff(value: String) = attr("chOff", value)
fun Tag<HTMLTableSectionElement>.chOff(value: Flow<String>) = attr("chOff", value)
fun Tag<HTMLTableSectionElement>.vAlign(value: String) = attr("vAlign", value)
fun Tag<HTMLTableSectionElement>.vAlign(value: Flow<String>) = attr("vAlign", value)
fun Tag<HTMLTableRowElement>.align(value: String) = attr("align", value)
fun Tag<HTMLTableRowElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLTableRowElement>.ch(value: String) = attr("ch", value)
fun Tag<HTMLTableRowElement>.ch(value: Flow<String>) = attr("ch", value)
fun Tag<HTMLTableRowElement>.chOff(value: String) = attr("chOff", value)
fun Tag<HTMLTableRowElement>.chOff(value: Flow<String>) = attr("chOff", value)
fun Tag<HTMLTableRowElement>.vAlign(value: String) = attr("vAlign", value)
fun Tag<HTMLTableRowElement>.vAlign(value: Flow<String>) = attr("vAlign", value)
fun Tag<HTMLTableRowElement>.bgColor(value: String) = attr("bgColor", value)
fun Tag<HTMLTableRowElement>.bgColor(value: Flow<String>) = attr("bgColor", value)
fun Tag<HTMLTableCellElement>.colSpan(value: Int) = attr("colSpan", value)
fun Tag<HTMLTableCellElement>.colSpan(value: Flow<Int>) = attr("colSpan", value)
fun Tag<HTMLTableCellElement>.rowSpan(value: Int) = attr("rowSpan", value)
fun Tag<HTMLTableCellElement>.rowSpan(value: Flow<Int>) = attr("rowSpan", value)
fun Tag<HTMLTableCellElement>.headers(value: String) = attr("headers", value)
fun Tag<HTMLTableCellElement>.headers(value: Flow<String>) = attr("headers", value)
fun Tag<HTMLTableCellElement>.scope(value: String) = attr("scope", value)
fun Tag<HTMLTableCellElement>.scope(value: Flow<String>) = attr("scope", value)
fun Tag<HTMLTableCellElement>.abbr(value: String) = attr("abbr", value)
fun Tag<HTMLTableCellElement>.abbr(value: Flow<String>) = attr("abbr", value)
fun Tag<HTMLTableCellElement>.align(value: String) = attr("align", value)
fun Tag<HTMLTableCellElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLTableCellElement>.axis(value: String) = attr("axis", value)
fun Tag<HTMLTableCellElement>.axis(value: Flow<String>) = attr("axis", value)
fun Tag<HTMLTableCellElement>.height(value: String) = attr("height", value)
fun Tag<HTMLTableCellElement>.height(value: Flow<String>) = attr("height", value)
fun Tag<HTMLTableCellElement>.width(value: String) = attr("width", value)
fun Tag<HTMLTableCellElement>.width(value: Flow<String>) = attr("width", value)
fun Tag<HTMLTableCellElement>.ch(value: String) = attr("ch", value)
fun Tag<HTMLTableCellElement>.ch(value: Flow<String>) = attr("ch", value)
fun Tag<HTMLTableCellElement>.chOff(value: String) = attr("chOff", value)
fun Tag<HTMLTableCellElement>.chOff(value: Flow<String>) = attr("chOff", value)
fun Tag<HTMLTableCellElement>.noWrap(value: Boolean, trueValue: String = "") = attr("noWrap", value, trueValue)
fun Tag<HTMLTableCellElement>.noWrap(value: Flow<Boolean>, trueValue: String = "") = attr("noWrap", value, trueValue)
fun Tag<HTMLTableCellElement>.vAlign(value: String) = attr("vAlign", value)
fun Tag<HTMLTableCellElement>.vAlign(value: Flow<String>) = attr("vAlign", value)
fun Tag<HTMLTableCellElement>.bgColor(value: String) = attr("bgColor", value)
fun Tag<HTMLTableCellElement>.bgColor(value: Flow<String>) = attr("bgColor", value)
fun Tag<HTMLFormElement>.acceptCharset(value: String) = attr("acceptCharset", value)
fun Tag<HTMLFormElement>.acceptCharset(value: Flow<String>) = attr("acceptCharset", value)
fun Tag<HTMLFormElement>.action(value: String) = attr("action", value)
fun Tag<HTMLFormElement>.action(value: Flow<String>) = attr("action", value)
fun Tag<HTMLFormElement>.autocomplete(value: String) = attr("autocomplete", value)
fun Tag<HTMLFormElement>.autocomplete(value: Flow<String>) = attr("autocomplete", value)
fun Tag<HTMLFormElement>.enctype(value: String) = attr("enctype", value)
fun Tag<HTMLFormElement>.enctype(value: Flow<String>) = attr("enctype", value)
fun Tag<HTMLFormElement>.encoding(value: String) = attr("encoding", value)
fun Tag<HTMLFormElement>.encoding(value: Flow<String>) = attr("encoding", value)
fun Tag<HTMLFormElement>.method(value: String) = attr("method", value)
fun Tag<HTMLFormElement>.method(value: Flow<String>) = attr("method", value)
fun Tag<HTMLFormElement>.name(value: String) = attr("name", value)
fun Tag<HTMLFormElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLFormElement>.noValidate(value: Boolean, trueValue: String = "") = attr("noValidate", value, trueValue)
fun Tag<HTMLFormElement>.noValidate(value: Flow<Boolean>, trueValue: String = "") = attr("noValidate", value, trueValue)
fun Tag<HTMLFormElement>.target(value: String) = attr("target", value)
fun Tag<HTMLFormElement>.target(value: Flow<String>) = attr("target", value)
fun Tag<HTMLLabelElement>.htmlFor(value: String) = attr("htmlFor", value)
fun Tag<HTMLLabelElement>.htmlFor(value: Flow<String>) = attr("htmlFor", value)
fun Tag<HTMLInputElement>.accept(value: String) = attr("accept", value)
fun Tag<HTMLInputElement>.accept(value: Flow<String>) = attr("accept", value)
fun Tag<HTMLInputElement>.alt(value: String) = attr("alt", value)
fun Tag<HTMLInputElement>.alt(value: Flow<String>) = attr("alt", value)
fun Tag<HTMLInputElement>.autocomplete(value: String) = attr("autocomplete", value)
fun Tag<HTMLInputElement>.autocomplete(value: Flow<String>) = attr("autocomplete", value)
fun Tag<HTMLInputElement>.autofocus(value: Boolean, trueValue: String = "") = attr("autofocus", value, trueValue)
fun Tag<HTMLInputElement>.autofocus(value: Flow<Boolean>, trueValue: String = "") = attr("autofocus", value, trueValue)
fun Tag<HTMLInputElement>.defaultChecked(value: Boolean, trueValue: String = "") = attr("defaultChecked", value, trueValue)
fun Tag<HTMLInputElement>.defaultChecked(value: Flow<Boolean>, trueValue: String = "") = attr("defaultChecked", value, trueValue)
fun Tag<HTMLInputElement>.checked(value: Boolean, trueValue: String = "") = attr("checked", value, trueValue)
fun Tag<HTMLInputElement>.checked(value: Flow<Boolean>, trueValue: String = "") = attr("checked", value, trueValue)
fun Tag<HTMLInputElement>.dirName(value: String) = attr("dirName", value)
fun Tag<HTMLInputElement>.dirName(value: Flow<String>) = attr("dirName", value)
fun Tag<HTMLInputElement>.disabled(value: Boolean, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLInputElement>.disabled(value: Flow<Boolean>, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLInputElement>.formAction(value: String) = attr("formAction", value)
fun Tag<HTMLInputElement>.formAction(value: Flow<String>) = attr("formAction", value)
fun Tag<HTMLInputElement>.formEnctype(value: String) = attr("formEnctype", value)
fun Tag<HTMLInputElement>.formEnctype(value: Flow<String>) = attr("formEnctype", value)
fun Tag<HTMLInputElement>.formMethod(value: String) = attr("formMethod", value)
fun Tag<HTMLInputElement>.formMethod(value: Flow<String>) = attr("formMethod", value)
fun Tag<HTMLInputElement>.formNoValidate(value: Boolean, trueValue: String = "") = attr("formNoValidate", value, trueValue)
fun Tag<HTMLInputElement>.formNoValidate(value: Flow<Boolean>, trueValue: String = "") = attr("formNoValidate", value, trueValue)
fun Tag<HTMLInputElement>.formTarget(value: String) = attr("formTarget", value)
fun Tag<HTMLInputElement>.formTarget(value: Flow<String>) = attr("formTarget", value)
fun Tag<HTMLInputElement>.height(value: Int) = attr("height", value)
fun Tag<HTMLInputElement>.height(value: Flow<Int>) = attr("height", value)
fun Tag<HTMLInputElement>.indeterminate(value: Boolean, trueValue: String = "") = attr("indeterminate", value, trueValue)
fun Tag<HTMLInputElement>.indeterminate(value: Flow<Boolean>, trueValue: String = "") = attr("indeterminate", value, trueValue)
fun Tag<HTMLInputElement>.inputMode(value: String) = attr("inputMode", value)
fun Tag<HTMLInputElement>.inputMode(value: Flow<String>) = attr("inputMode", value)
fun Tag<HTMLInputElement>.max(value: String) = attr("max", value)
fun Tag<HTMLInputElement>.max(value: Flow<String>) = attr("max", value)
fun Tag<HTMLInputElement>.maxLength(value: Int) = attr("maxLength", value)
fun Tag<HTMLInputElement>.maxLength(value: Flow<Int>) = attr("maxLength", value)
fun Tag<HTMLInputElement>.min(value: String) = attr("min", value)
fun Tag<HTMLInputElement>.min(value: Flow<String>) = attr("min", value)
fun Tag<HTMLInputElement>.minLength(value: Int) = attr("minLength", value)
fun Tag<HTMLInputElement>.minLength(value: Flow<Int>) = attr("minLength", value)
fun Tag<HTMLInputElement>.multiple(value: Boolean, trueValue: String = "") = attr("multiple", value, trueValue)
fun Tag<HTMLInputElement>.multiple(value: Flow<Boolean>, trueValue: String = "") = attr("multiple", value, trueValue)
fun Tag<HTMLInputElement>.name(value: String) = attr("name", value)
fun Tag<HTMLInputElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLInputElement>.pattern(value: String) = attr("pattern", value)
fun Tag<HTMLInputElement>.pattern(value: Flow<String>) = attr("pattern", value)
fun Tag<HTMLInputElement>.placeholder(value: String) = attr("placeholder", value)
fun Tag<HTMLInputElement>.placeholder(value: Flow<String>) = attr("placeholder", value)
fun Tag<HTMLInputElement>.readOnly(value: Boolean, trueValue: String = "") = attr("readOnly", value, trueValue)
fun Tag<HTMLInputElement>.readOnly(value: Flow<Boolean>, trueValue: String = "") = attr("readOnly", value, trueValue)
fun Tag<HTMLInputElement>.required(value: Boolean, trueValue: String = "") = attr("required", value, trueValue)
fun Tag<HTMLInputElement>.required(value: Flow<Boolean>, trueValue: String = "") = attr("required", value, trueValue)
fun Tag<HTMLInputElement>.size(value: Int) = attr("size", value)
fun Tag<HTMLInputElement>.size(value: Flow<Int>) = attr("size", value)
fun Tag<HTMLInputElement>.src(value: String) = attr("src", value)
fun Tag<HTMLInputElement>.src(value: Flow<String>) = attr("src", value)
fun Tag<HTMLInputElement>.step(value: String) = attr("step", value)
fun Tag<HTMLInputElement>.step(value: Flow<String>) = attr("step", value)
fun Tag<HTMLInputElement>.type(value: String) = attr("type", value)
fun Tag<HTMLInputElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLInputElement>.defaultValue(value: String) = attr("defaultValue", value)
fun Tag<HTMLInputElement>.defaultValue(value: Flow<String>) = attr("defaultValue", value)
fun Tag<HTMLInputElement>.value(value: String) = attr("value", value)
fun Tag<HTMLInputElement>.value(value: Flow<String>) = attr("value", value)
fun Tag<HTMLInputElement>.valueAsDate(value: String) = attr("valueAsDate", value)
fun Tag<HTMLInputElement>.valueAsDate(value: Flow<String>) = attr("valueAsDate", value)
fun Tag<HTMLInputElement>.valueAsNumber(value: Double) = attr("valueAsNumber", value)
fun Tag<HTMLInputElement>.valueAsNumber(value: Flow<Double>) = attr("valueAsNumber", value)
fun Tag<HTMLInputElement>.width(value: Int) = attr("width", value)
fun Tag<HTMLInputElement>.width(value: Flow<Int>) = attr("width", value)
fun Tag<HTMLInputElement>.selectionStart(value: Int?) = attr("selectionStart", value)
fun Tag<HTMLInputElement>.selectionStart(value: Flow<Int?>) = attr("selectionStart", value)
fun Tag<HTMLInputElement>.selectionEnd(value: Int?) = attr("selectionEnd", value)
fun Tag<HTMLInputElement>.selectionEnd(value: Flow<Int?>) = attr("selectionEnd", value)
fun Tag<HTMLInputElement>.selectionDirection(value: String?) = attr("selectionDirection", value)
fun Tag<HTMLInputElement>.selectionDirection(value: Flow<String?>) = attr("selectionDirection", value)
fun Tag<HTMLInputElement>.align(value: String) = attr("align", value)
fun Tag<HTMLInputElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLInputElement>.useMap(value: String) = attr("useMap", value)
fun Tag<HTMLInputElement>.useMap(value: Flow<String>) = attr("useMap", value)
fun Tag<HTMLButtonElement>.autofocus(value: Boolean, trueValue: String = "") = attr("autofocus", value, trueValue)
fun Tag<HTMLButtonElement>.autofocus(value: Flow<Boolean>, trueValue: String = "") = attr("autofocus", value, trueValue)
fun Tag<HTMLButtonElement>.disabled(value: Boolean, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLButtonElement>.disabled(value: Flow<Boolean>, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLButtonElement>.formAction(value: String) = attr("formAction", value)
fun Tag<HTMLButtonElement>.formAction(value: Flow<String>) = attr("formAction", value)
fun Tag<HTMLButtonElement>.formEnctype(value: String) = attr("formEnctype", value)
fun Tag<HTMLButtonElement>.formEnctype(value: Flow<String>) = attr("formEnctype", value)
fun Tag<HTMLButtonElement>.formMethod(value: String) = attr("formMethod", value)
fun Tag<HTMLButtonElement>.formMethod(value: Flow<String>) = attr("formMethod", value)
fun Tag<HTMLButtonElement>.formNoValidate(value: Boolean, trueValue: String = "") = attr("formNoValidate", value, trueValue)
fun Tag<HTMLButtonElement>.formNoValidate(value: Flow<Boolean>, trueValue: String = "") = attr("formNoValidate", value, trueValue)
fun Tag<HTMLButtonElement>.formTarget(value: String) = attr("formTarget", value)
fun Tag<HTMLButtonElement>.formTarget(value: Flow<String>) = attr("formTarget", value)
fun Tag<HTMLButtonElement>.name(value: String) = attr("name", value)
fun Tag<HTMLButtonElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLButtonElement>.type(value: String) = attr("type", value)
fun Tag<HTMLButtonElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLButtonElement>.value(value: String) = attr("value", value)
fun Tag<HTMLButtonElement>.value(value: Flow<String>) = attr("value", value)
fun Tag<HTMLButtonElement>.menu(value: HTMLMenuElement?) = attr("menu", value)
fun Tag<HTMLButtonElement>.menu(value: Flow<HTMLMenuElement?>) = attr("menu", value)
fun Tag<HTMLSelectElement>.autocomplete(value: String) = attr("autocomplete", value)
fun Tag<HTMLSelectElement>.autocomplete(value: Flow<String>) = attr("autocomplete", value)
fun Tag<HTMLSelectElement>.autofocus(value: Boolean, trueValue: String = "") = attr("autofocus", value, trueValue)
fun Tag<HTMLSelectElement>.autofocus(value: Flow<Boolean>, trueValue: String = "") = attr("autofocus", value, trueValue)
fun Tag<HTMLSelectElement>.disabled(value: Boolean, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLSelectElement>.disabled(value: Flow<Boolean>, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLSelectElement>.multiple(value: Boolean, trueValue: String = "") = attr("multiple", value, trueValue)
fun Tag<HTMLSelectElement>.multiple(value: Flow<Boolean>, trueValue: String = "") = attr("multiple", value, trueValue)
fun Tag<HTMLSelectElement>.name(value: String) = attr("name", value)
fun Tag<HTMLSelectElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLSelectElement>.required(value: Boolean, trueValue: String = "") = attr("required", value, trueValue)
fun Tag<HTMLSelectElement>.required(value: Flow<Boolean>, trueValue: String = "") = attr("required", value, trueValue)
fun Tag<HTMLSelectElement>.size(value: Int) = attr("size", value)
fun Tag<HTMLSelectElement>.size(value: Flow<Int>) = attr("size", value)
fun Tag<HTMLSelectElement>.selectedIndex(value: Int) = attr("selectedIndex", value)
fun Tag<HTMLSelectElement>.selectedIndex(value: Flow<Int>) = attr("selectedIndex", value)
fun Tag<HTMLSelectElement>.value(value: String) = attr("value", value)
fun Tag<HTMLSelectElement>.value(value: Flow<String>) = attr("value", value)
fun Tag<HTMLOptGroupElement>.disabled(value: Boolean, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLOptGroupElement>.disabled(value: Flow<Boolean>, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLOptGroupElement>.label(value: String) = attr("label", value)
fun Tag<HTMLOptGroupElement>.label(value: Flow<String>) = attr("label", value)
fun Tag<HTMLOptionElement>.disabled(value: Boolean, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLOptionElement>.disabled(value: Flow<Boolean>, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLOptionElement>.label(value: String) = attr("label", value)
fun Tag<HTMLOptionElement>.label(value: Flow<String>) = attr("label", value)
fun Tag<HTMLOptionElement>.defaultSelected(value: Boolean, trueValue: String = "") = attr("defaultSelected", value, trueValue)
fun Tag<HTMLOptionElement>.defaultSelected(value: Flow<Boolean>, trueValue: String = "") = attr("defaultSelected", value, trueValue)
fun Tag<HTMLOptionElement>.selected(value: Boolean, trueValue: String = "") = attr("selected", value, trueValue)
fun Tag<HTMLOptionElement>.selected(value: Flow<Boolean>, trueValue: String = "") = attr("selected", value, trueValue)
fun Tag<HTMLOptionElement>.value(value: String) = attr("value", value)
fun Tag<HTMLOptionElement>.value(value: Flow<String>) = attr("value", value)
fun Tag<HTMLOptionElement>.text(value: String) = attr("text", value)
fun Tag<HTMLOptionElement>.text(value: Flow<String>) = attr("text", value)
fun Tag<HTMLTextAreaElement>.autocomplete(value: String) = attr("autocomplete", value)
fun Tag<HTMLTextAreaElement>.autocomplete(value: Flow<String>) = attr("autocomplete", value)
fun Tag<HTMLTextAreaElement>.autofocus(value: Boolean, trueValue: String = "") = attr("autofocus", value, trueValue)
fun Tag<HTMLTextAreaElement>.autofocus(value: Flow<Boolean>, trueValue: String = "") = attr("autofocus", value, trueValue)
fun Tag<HTMLTextAreaElement>.cols(value: Int) = attr("cols", value)
fun Tag<HTMLTextAreaElement>.cols(value: Flow<Int>) = attr("cols", value)
fun Tag<HTMLTextAreaElement>.dirName(value: String) = attr("dirName", value)
fun Tag<HTMLTextAreaElement>.dirName(value: Flow<String>) = attr("dirName", value)
fun Tag<HTMLTextAreaElement>.disabled(value: Boolean, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLTextAreaElement>.disabled(value: Flow<Boolean>, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLTextAreaElement>.inputMode(value: String) = attr("inputMode", value)
fun Tag<HTMLTextAreaElement>.inputMode(value: Flow<String>) = attr("inputMode", value)
fun Tag<HTMLTextAreaElement>.maxLength(value: Int) = attr("maxLength", value)
fun Tag<HTMLTextAreaElement>.maxLength(value: Flow<Int>) = attr("maxLength", value)
fun Tag<HTMLTextAreaElement>.minLength(value: Int) = attr("minLength", value)
fun Tag<HTMLTextAreaElement>.minLength(value: Flow<Int>) = attr("minLength", value)
fun Tag<HTMLTextAreaElement>.name(value: String) = attr("name", value)
fun Tag<HTMLTextAreaElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLTextAreaElement>.placeholder(value: String) = attr("placeholder", value)
fun Tag<HTMLTextAreaElement>.placeholder(value: Flow<String>) = attr("placeholder", value)
fun Tag<HTMLTextAreaElement>.readOnly(value: Boolean, trueValue: String = "") = attr("readOnly", value, trueValue)
fun Tag<HTMLTextAreaElement>.readOnly(value: Flow<Boolean>, trueValue: String = "") = attr("readOnly", value, trueValue)
fun Tag<HTMLTextAreaElement>.required(value: Boolean, trueValue: String = "") = attr("required", value, trueValue)
fun Tag<HTMLTextAreaElement>.required(value: Flow<Boolean>, trueValue: String = "") = attr("required", value, trueValue)
fun Tag<HTMLTextAreaElement>.rows(value: Int) = attr("rows", value)
fun Tag<HTMLTextAreaElement>.rows(value: Flow<Int>) = attr("rows", value)
fun Tag<HTMLTextAreaElement>.wrap(value: String) = attr("wrap", value)
fun Tag<HTMLTextAreaElement>.wrap(value: Flow<String>) = attr("wrap", value)
fun Tag<HTMLTextAreaElement>.defaultValue(value: String) = attr("defaultValue", value)
fun Tag<HTMLTextAreaElement>.defaultValue(value: Flow<String>) = attr("defaultValue", value)
fun Tag<HTMLTextAreaElement>.value(value: String) = attr("value", value)
fun Tag<HTMLTextAreaElement>.value(value: Flow<String>) = attr("value", value)
fun Tag<HTMLTextAreaElement>.selectionStart(value: Int?) = attr("selectionStart", value)
fun Tag<HTMLTextAreaElement>.selectionStart(value: Flow<Int?>) = attr("selectionStart", value)
fun Tag<HTMLTextAreaElement>.selectionEnd(value: Int?) = attr("selectionEnd", value)
fun Tag<HTMLTextAreaElement>.selectionEnd(value: Flow<Int?>) = attr("selectionEnd", value)
fun Tag<HTMLTextAreaElement>.selectionDirection(value: String?) = attr("selectionDirection", value)
fun Tag<HTMLTextAreaElement>.selectionDirection(value: Flow<String?>) = attr("selectionDirection", value)
fun Tag<HTMLKeygenElement>.autofocus(value: Boolean, trueValue: String = "") = attr("autofocus", value, trueValue)
fun Tag<HTMLKeygenElement>.autofocus(value: Flow<Boolean>, trueValue: String = "") = attr("autofocus", value, trueValue)
fun Tag<HTMLKeygenElement>.challenge(value: String) = attr("challenge", value)
fun Tag<HTMLKeygenElement>.challenge(value: Flow<String>) = attr("challenge", value)
fun Tag<HTMLKeygenElement>.disabled(value: Boolean, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLKeygenElement>.disabled(value: Flow<Boolean>, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLKeygenElement>.keytype(value: String) = attr("keytype", value)
fun Tag<HTMLKeygenElement>.keytype(value: Flow<String>) = attr("keytype", value)
fun Tag<HTMLKeygenElement>.name(value: String) = attr("name", value)
fun Tag<HTMLKeygenElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLOutputElement>.name(value: String) = attr("name", value)
fun Tag<HTMLOutputElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLOutputElement>.defaultValue(value: String) = attr("defaultValue", value)
fun Tag<HTMLOutputElement>.defaultValue(value: Flow<String>) = attr("defaultValue", value)
fun Tag<HTMLOutputElement>.value(value: String) = attr("value", value)
fun Tag<HTMLOutputElement>.value(value: Flow<String>) = attr("value", value)
fun Tag<HTMLProgressElement>.value(value: Double) = attr("value", value)
fun Tag<HTMLProgressElement>.value(value: Flow<Double>) = attr("value", value)
fun Tag<HTMLProgressElement>.max(value: Double) = attr("max", value)
fun Tag<HTMLProgressElement>.max(value: Flow<Double>) = attr("max", value)
fun Tag<HTMLMeterElement>.value(value: Double) = attr("value", value)
fun Tag<HTMLMeterElement>.value(value: Flow<Double>) = attr("value", value)
fun Tag<HTMLMeterElement>.min(value: Double) = attr("min", value)
fun Tag<HTMLMeterElement>.min(value: Flow<Double>) = attr("min", value)
fun Tag<HTMLMeterElement>.max(value: Double) = attr("max", value)
fun Tag<HTMLMeterElement>.max(value: Flow<Double>) = attr("max", value)
fun Tag<HTMLMeterElement>.low(value: Double) = attr("low", value)
fun Tag<HTMLMeterElement>.low(value: Flow<Double>) = attr("low", value)
fun Tag<HTMLMeterElement>.high(value: Double) = attr("high", value)
fun Tag<HTMLMeterElement>.high(value: Flow<Double>) = attr("high", value)
fun Tag<HTMLMeterElement>.optimum(value: Double) = attr("optimum", value)
fun Tag<HTMLMeterElement>.optimum(value: Flow<Double>) = attr("optimum", value)
fun Tag<HTMLFieldSetElement>.disabled(value: Boolean, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLFieldSetElement>.disabled(value: Flow<Boolean>, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLFieldSetElement>.name(value: String) = attr("name", value)
fun Tag<HTMLFieldSetElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLLegendElement>.align(value: String) = attr("align", value)
fun Tag<HTMLLegendElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLDetailsElement>.open(value: Boolean, trueValue: String = "") = attr("open", value, trueValue)
fun Tag<HTMLDetailsElement>.open(value: Flow<Boolean>, trueValue: String = "") = attr("open", value, trueValue)
fun Tag<HTMLMenuElement>.type(value: String) = attr("type", value)
fun Tag<HTMLMenuElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLMenuElement>.label(value: String) = attr("label", value)
fun Tag<HTMLMenuElement>.label(value: Flow<String>) = attr("label", value)
fun Tag<HTMLMenuElement>.compact(value: Boolean, trueValue: String = "") = attr("compact", value, trueValue)
fun Tag<HTMLMenuElement>.compact(value: Flow<Boolean>, trueValue: String = "") = attr("compact", value, trueValue)
fun Tag<HTMLMenuItemElement>.type(value: String) = attr("type", value)
fun Tag<HTMLMenuItemElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLMenuItemElement>.label(value: String) = attr("label", value)
fun Tag<HTMLMenuItemElement>.label(value: Flow<String>) = attr("label", value)
fun Tag<HTMLMenuItemElement>.icon(value: String) = attr("icon", value)
fun Tag<HTMLMenuItemElement>.icon(value: Flow<String>) = attr("icon", value)
fun Tag<HTMLMenuItemElement>.disabled(value: Boolean, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLMenuItemElement>.disabled(value: Flow<Boolean>, trueValue: String = "") = attr("disabled", value, trueValue)
fun Tag<HTMLMenuItemElement>.checked(value: Boolean, trueValue: String = "") = attr("checked", value, trueValue)
fun Tag<HTMLMenuItemElement>.checked(value: Flow<Boolean>, trueValue: String = "") = attr("checked", value, trueValue)
fun Tag<HTMLMenuItemElement>.radiogroup(value: String) = attr("radiogroup", value)
fun Tag<HTMLMenuItemElement>.radiogroup(value: Flow<String>) = attr("radiogroup", value)
fun Tag<HTMLMenuItemElement>.default(value: Boolean, trueValue: String = "") = attr("default", value, trueValue)
fun Tag<HTMLMenuItemElement>.default(value: Flow<Boolean>, trueValue: String = "") = attr("default", value, trueValue)
fun Tag<HTMLDialogElement>.open(value: Boolean, trueValue: String = "") = attr("open", value, trueValue)
fun Tag<HTMLDialogElement>.open(value: Flow<Boolean>, trueValue: String = "") = attr("open", value, trueValue)
fun Tag<HTMLDialogElement>.returnValue(value: String) = attr("returnValue", value)
fun Tag<HTMLDialogElement>.returnValue(value: Flow<String>) = attr("returnValue", value)
fun Tag<HTMLScriptElement>.src(value: String) = attr("src", value)
fun Tag<HTMLScriptElement>.src(value: Flow<String>) = attr("src", value)
fun Tag<HTMLScriptElement>.type(value: String) = attr("type", value)
fun Tag<HTMLScriptElement>.type(value: Flow<String>) = attr("type", value)
fun Tag<HTMLScriptElement>.charset(value: String) = attr("charset", value)
fun Tag<HTMLScriptElement>.charset(value: Flow<String>) = attr("charset", value)
fun Tag<HTMLScriptElement>.async(value: Boolean, trueValue: String = "") = attr("async", value, trueValue)
fun Tag<HTMLScriptElement>.async(value: Flow<Boolean>, trueValue: String = "") = attr("async", value, trueValue)
fun Tag<HTMLScriptElement>.defer(value: Boolean, trueValue: String = "") = attr("defer", value, trueValue)
fun Tag<HTMLScriptElement>.defer(value: Flow<Boolean>, trueValue: String = "") = attr("defer", value, trueValue)
fun Tag<HTMLScriptElement>.crossOrigin(value: String?) = attr("crossOrigin", value)
fun Tag<HTMLScriptElement>.crossOrigin(value: Flow<String?>) = attr("crossOrigin", value)
fun Tag<HTMLScriptElement>.text(value: String) = attr("text", value)
fun Tag<HTMLScriptElement>.text(value: Flow<String>) = attr("text", value)
fun Tag<HTMLScriptElement>.nonce(value: String) = attr("nonce", value)
fun Tag<HTMLScriptElement>.nonce(value: Flow<String>) = attr("nonce", value)
fun Tag<HTMLScriptElement>.event(value: String) = attr("event", value)
fun Tag<HTMLScriptElement>.event(value: Flow<String>) = attr("event", value)
fun Tag<HTMLScriptElement>.htmlFor(value: String) = attr("htmlFor", value)
fun Tag<HTMLScriptElement>.htmlFor(value: Flow<String>) = attr("htmlFor", value)
fun Tag<HTMLSlotElement>.name(value: String) = attr("name", value)
fun Tag<HTMLSlotElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLCanvasElement>.width(value: Int) = attr("width", value)
fun Tag<HTMLCanvasElement>.width(value: Flow<Int>) = attr("width", value)
fun Tag<HTMLCanvasElement>.height(value: Int) = attr("height", value)
fun Tag<HTMLCanvasElement>.height(value: Flow<Int>) = attr("height", value)
fun Tag<HTMLAppletElement>.align(value: String) = attr("align", value)
fun Tag<HTMLAppletElement>.align(value: Flow<String>) = attr("align", value)
fun Tag<HTMLAppletElement>.alt(value: String) = attr("alt", value)
fun Tag<HTMLAppletElement>.alt(value: Flow<String>) = attr("alt", value)
fun Tag<HTMLAppletElement>.archive(value: String) = attr("archive", value)
fun Tag<HTMLAppletElement>.archive(value: Flow<String>) = attr("archive", value)
fun Tag<HTMLAppletElement>.code(value: String) = attr("code", value)
fun Tag<HTMLAppletElement>.code(value: Flow<String>) = attr("code", value)
fun Tag<HTMLAppletElement>.codeBase(value: String) = attr("codeBase", value)
fun Tag<HTMLAppletElement>.codeBase(value: Flow<String>) = attr("codeBase", value)
fun Tag<HTMLAppletElement>.height(value: String) = attr("height", value)
fun Tag<HTMLAppletElement>.height(value: Flow<String>) = attr("height", value)
fun Tag<HTMLAppletElement>.hspace(value: Int) = attr("hspace", value)
fun Tag<HTMLAppletElement>.hspace(value: Flow<Int>) = attr("hspace", value)
fun Tag<HTMLAppletElement>.name(value: String) = attr("name", value)
fun Tag<HTMLAppletElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLAppletElement>._object(value: String) = attr("_object", value)
fun Tag<HTMLAppletElement>._object(value: Flow<String>) = attr("_object", value)
fun Tag<HTMLAppletElement>.vspace(value: Int) = attr("vspace", value)
fun Tag<HTMLAppletElement>.vspace(value: Flow<Int>) = attr("vspace", value)
fun Tag<HTMLAppletElement>.width(value: String) = attr("width", value)
fun Tag<HTMLAppletElement>.width(value: Flow<String>) = attr("width", value)
fun Tag<HTMLMarqueeElement>.behavior(value: String) = attr("behavior", value)
fun Tag<HTMLMarqueeElement>.behavior(value: Flow<String>) = attr("behavior", value)
fun Tag<HTMLMarqueeElement>.bgColor(value: String) = attr("bgColor", value)
fun Tag<HTMLMarqueeElement>.bgColor(value: Flow<String>) = attr("bgColor", value)
fun Tag<HTMLMarqueeElement>.direction(value: String) = attr("direction", value)
fun Tag<HTMLMarqueeElement>.direction(value: Flow<String>) = attr("direction", value)
fun Tag<HTMLMarqueeElement>.height(value: String) = attr("height", value)
fun Tag<HTMLMarqueeElement>.height(value: Flow<String>) = attr("height", value)
fun Tag<HTMLMarqueeElement>.hspace(value: Int) = attr("hspace", value)
fun Tag<HTMLMarqueeElement>.hspace(value: Flow<Int>) = attr("hspace", value)
fun Tag<HTMLMarqueeElement>.loop(value: Int) = attr("loop", value)
fun Tag<HTMLMarqueeElement>.loop(value: Flow<Int>) = attr("loop", value)
fun Tag<HTMLMarqueeElement>.scrollAmount(value: Int) = attr("scrollAmount", value)
fun Tag<HTMLMarqueeElement>.scrollAmount(value: Flow<Int>) = attr("scrollAmount", value)
fun Tag<HTMLMarqueeElement>.scrollDelay(value: Int) = attr("scrollDelay", value)
fun Tag<HTMLMarqueeElement>.scrollDelay(value: Flow<Int>) = attr("scrollDelay", value)
fun Tag<HTMLMarqueeElement>.trueSpeed(value: Boolean, trueValue: String = "") = attr("trueSpeed", value, trueValue)
fun Tag<HTMLMarqueeElement>.trueSpeed(value: Flow<Boolean>, trueValue: String = "") = attr("trueSpeed", value, trueValue)
fun Tag<HTMLMarqueeElement>.vspace(value: Int) = attr("vspace", value)
fun Tag<HTMLMarqueeElement>.vspace(value: Flow<Int>) = attr("vspace", value)
fun Tag<HTMLMarqueeElement>.width(value: String) = attr("width", value)
fun Tag<HTMLMarqueeElement>.width(value: Flow<String>) = attr("width", value)
fun Tag<HTMLMarqueeElement>.onbounce(value: ((Event) -> dynamic)?) = attr("onbounce", value)
fun Tag<HTMLMarqueeElement>.onbounce(value: Flow<((Event) -> dynamic)?>) = attr("onbounce", value)
fun Tag<HTMLMarqueeElement>.onfinish(value: ((Event) -> dynamic)?) = attr("onfinish", value)
fun Tag<HTMLMarqueeElement>.onfinish(value: Flow<((Event) -> dynamic)?>) = attr("onfinish", value)
fun Tag<HTMLMarqueeElement>.onstart(value: ((Event) -> dynamic)?) = attr("onstart", value)
fun Tag<HTMLMarqueeElement>.onstart(value: Flow<((Event) -> dynamic)?>) = attr("onstart", value)
fun Tag<HTMLFrameSetElement>.cols(value: String) = attr("cols", value)
fun Tag<HTMLFrameSetElement>.cols(value: Flow<String>) = attr("cols", value)
fun Tag<HTMLFrameSetElement>.rows(value: String) = attr("rows", value)
fun Tag<HTMLFrameSetElement>.rows(value: Flow<String>) = attr("rows", value)
fun Tag<HTMLFrameElement>.name(value: String) = attr("name", value)
fun Tag<HTMLFrameElement>.name(value: Flow<String>) = attr("name", value)
fun Tag<HTMLFrameElement>.scrolling(value: String) = attr("scrolling", value)
fun Tag<HTMLFrameElement>.scrolling(value: Flow<String>) = attr("scrolling", value)
fun Tag<HTMLFrameElement>.src(value: String) = attr("src", value)
fun Tag<HTMLFrameElement>.src(value: Flow<String>) = attr("src", value)
fun Tag<HTMLFrameElement>.frameBorder(value: String) = attr("frameBorder", value)
fun Tag<HTMLFrameElement>.frameBorder(value: Flow<String>) = attr("frameBorder", value)
fun Tag<HTMLFrameElement>.longDesc(value: String) = attr("longDesc", value)
fun Tag<HTMLFrameElement>.longDesc(value: Flow<String>) = attr("longDesc", value)
fun Tag<HTMLFrameElement>.noResize(value: Boolean, trueValue: String = "") = attr("noResize", value, trueValue)
fun Tag<HTMLFrameElement>.noResize(value: Flow<Boolean>, trueValue: String = "") = attr("noResize", value, trueValue)
fun Tag<HTMLFrameElement>.marginHeight(value: String) = attr("marginHeight", value)
fun Tag<HTMLFrameElement>.marginHeight(value: Flow<String>) = attr("marginHeight", value)
fun Tag<HTMLFrameElement>.marginWidth(value: String) = attr("marginWidth", value)
fun Tag<HTMLFrameElement>.marginWidth(value: Flow<String>) = attr("marginWidth", value)
fun Tag<HTMLDirectoryElement>.compact(value: Boolean, trueValue: String = "") = attr("compact", value, trueValue)
fun Tag<HTMLDirectoryElement>.compact(value: Flow<Boolean>, trueValue: String = "") = attr("compact", value, trueValue)
fun Tag<HTMLFontElement>.color(value: String) = attr("color", value)
fun Tag<HTMLFontElement>.color(value: Flow<String>) = attr("color", value)
fun Tag<HTMLFontElement>.face(value: String) = attr("face", value)
fun Tag<HTMLFontElement>.face(value: Flow<String>) = attr("face", value)
fun Tag<HTMLFontElement>.size(value: String) = attr("size", value)
fun Tag<HTMLFontElement>.size(value: Flow<String>) = attr("size", value)

//added by hand

fun SvgTag<SVGElement>.viewBox(value: String) = attr("viewBox", value)
fun SvgTag<SVGElement>.viewBox(value: Flow<String>) = attr("viewBox", value)

fun SvgTag<SVGElement>.fill(value: String) = attr("fill", value)
fun SvgTag<SVGElement>.fill(value: Flow<String>) = attr("fill", value)

fun SvgTag<SVGPathElement>.d(value: String) = attr("fill", value)
fun SvgTag<SVGPathElement>.d(value: Flow<String>) = attr("fill", value)
