package dev.fritz2.lenses

import com.tschuchort.compiletesting.KotlinCompilation
import com.tschuchort.compiletesting.SourceFile
import com.tschuchort.compiletesting.symbolProcessorProviders
import org.assertj.core.api.Assertions
import java.io.File
import java.nio.charset.StandardCharsets
import kotlin.io.path.ExperimentalPathApi
import kotlin.io.path.createTempDirectory
import kotlin.test.Test

class LensesProcessorTests {

    @ExperimentalPathApi
    private fun compileSource(vararg source: SourceFile) = KotlinCompilation().apply {
        sources = source.toList()
        symbolProcessorProviders = listOf(LensesGeneratorProcessorProvider())
        workingDir = createTempDirectory("fritz2-tests").toFile()
        inheritClassPath = true
        verbose = false
    }.compile()

    // workaround copied by https://github.com/tschuchortdev/kotlin-compile-testing/issues/129#issuecomment-804390310
    internal val KotlinCompilation.Result.workingDir: File
        get() =
            outputDirectory.parentFile!!

    // workaround inspired by https://github.com/tschuchortdev/kotlin-compile-testing/issues/129#issuecomment-804390310
    val KotlinCompilation.Result.kspGeneratedSources: List<File>
        get() {
            val kspWorkingDir = workingDir.resolve("ksp")
            val kspGeneratedDir = kspWorkingDir.resolve("sources")
            val kotlinGeneratedDir = kspGeneratedDir.resolve("kotlin")
            val javaGeneratedDir = kspGeneratedDir.resolve("java")
            return kotlinGeneratedDir.walkTopDown().toList() +
                    javaGeneratedDir.walkTopDown()
        }

    @ExperimentalPathApi
    @Test
    fun `validate lenses generation works`() {
        val kotlinSource = SourceFile.kotlin(
            "file_lenses.kt", """
                package dev.fritz2.lensetest

                import dev.fritz2.lenses.Lenses

                class MyType

                @Lenses
                data class Foo(
                    val bar: Int,
                    val baz: String,
                    val fooBar: MyType
                ) {
                    companion object
                }
            """
        )

        val compilationResult = compileSource(kotlinSource)

        Assertions.assertThat(compilationResult.exitCode).isEqualTo(KotlinCompilation.ExitCode.OK)
        Assertions.assertThat(
            compilationResult.kspGeneratedSources.find { it.name == "FooLenses.kt" }
        ).usingCharset(StandardCharsets.UTF_8).hasContent(
            """
            |// GENERATED by fritz2 - NEVER CHANGE CONTENT MANUALLY!
            |package dev.fritz2.lensetest
            |
            |import dev.fritz2.lenses.Lens
            |import dev.fritz2.lenses.buildLens
            |import kotlin.Int
            |import kotlin.String
            |
            |public object L {
            |  public object Foo {
            |    public val bar: Lens<dev.fritz2.lensetest.Foo, Int> = buildLens("bar", { it.bar }, { p, v ->
            |        p.copy(bar = v)})
            |
            |    public val baz: Lens<dev.fritz2.lensetest.Foo, String> = buildLens("baz", { it.baz }, { p, v ->
            |        p.copy(baz = v)})
            |
            |    public val fooBar: Lens<dev.fritz2.lensetest.Foo, MyType> = buildLens("fooBar", { it.fooBar }, {
            |        p, v -> p.copy(fooBar = v)})
            |  }
            |}
            """.trimMargin()
        )

    }
}